### ISSUE TITLE
[documentation][samples] Upgrade TODO apps to 2.0

### ISSUE THREAD

**Issue by ilhan007** [UI5/webcomponents#9466]
### **Issue Description**
Upgrade all TODO apps to 2.0

### **Issue Type**

- [x] [React](https://github.com/SAP-samples/ui5-webcomponents-sample-react)
- [ ] [Angular](https://github.com/SAP-samples/ui5-webcomponents-sample-angular)
- [x] [Vue](https://github.com/SAP-samples/ui5-webcomponents-sample-vue) https://github.com/SAP-samples/ui5-webcomponents-sample-vue/pull/87
- [ ] [Svelte](https://github.com/SAP-samples/ui5-webcomponents-sample-svelte) https://github.com/SAP-samples/ui5-webcomponents-sample-svelte/pull/13
